* SEP

SEP (Search Embedded, Print) is a CLI tool that reads =stdin=, parses the text and embeds a query and the text to find a specific chunk that is closest to the query. The project is not vibecoded.

** Installation
SEP is not yet on any package managers. Make sure you have cargo installed, type

= https://github.com/ACatCoder-builds/sep.git =

Then type:

= # cargo build --release =

The executable is available under =./target/release/sep= and can be used as follows:

= ./target/release/sep <ARGS> =

*NOTE*: We will use =sep= instead of =./target/release/sep= for the rest of this document. If you wish to copy lines, replace =sep= with the path of the executable (=target/release/sep=)

** Usage
Suppose you have a text file called =cat_test.txt=. To find =What do cats eat?=, use:
= cat cat_test.txt | sep "What do cats eat?" =
If you want to write the output to a file called =result.txt=, do:
= cat cat_test.txt | sep "What do cats eat?" -r > result.txt =
The `r` flag removes the color from the outputs, which does not look as good in the terminal, but it means there are no "special" characters in the file that would control the character.

** Goals

SEP's goal is to become a utility for researching where you can find where something is mentioned, ideally in a text file. As such, it relies heavily on sentences and punctuation to create meaningfully-sized chunks. Proper chunking of code is not a goal. Reading files from a file instead of having to use =cat= is not a goal.

** Contributing

We enforce following rules onto PRs and the project as a whole:

- The code should not panic. Any panic should be considered a bug and reported.
- Unsafe code is banned from the project.
- Any PRs that use AI must be labeled as using AI, both in the PRs description and through a code comment.
- Use =TODO= instead of =FIXME=.
